export const DASHBOARD = '/dashboard'
export const LANDING = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const SECRET = '/secret'
export const PROJECT_DETAIL = '/project/:id'
export const CREATE_PROJECT = '/create'
